Revert "Make NewInstanceString test returned String contents."
Bug: 30951794

Flakes:
    org.apache.harmony.jpda.tests.framework.TestErrorException: org.apache.harmony.jpda.tests.framework.jdwp.exceptions.TimeoutException: Connection was closed
    	at org.apache.harmony.jpda.tests.framework.jdwp.VmMirror.performCommand(VmMirror.java:1944)
    	at org.apache.harmony.jpda.tests.jdwp.share.JDWPTestCase.getStringValue(JDWPTestCase.java:424)
    	at org.apache.harmony.jpda.tests.jdwp.ClassType.NewInstanceStringTest.runTestNewInstanceString(NewInstanceStringTest.java:278)
    	at org.apache.harmony.jpda.tests.jdwp.ClassType.NewInstanceStringTest.testNewInstanceString_StringBuilderConstructor(NewInstanceStringTest.java:256)
    Caused by: org.apache.harmony.jpda.tests.framework.jdwp.exceptions.TimeoutException: Connection was closed
    	at org.apache.harmony.jpda.tests.framework.jdwp.PacketDispatcher.run(PacketDispatcher.java:599)
  org.apache.harmony.jpda.tests.jdwp.ClassType.NewInstanceStringTest#testNewInstanceString_StringBuilderConstructor FAIL (EXEC_FAILED)


This reverts commit be5386b80c1e649da468c1c0e2e247784c8e9991.

Change-Id: Iae63c88942c46ca462a397cbab4f81af06cad8c0